import { join } from "node:path";

import type { EventFacts } from "@/lib/types";

import { c } from "./tokens";
import { loadFont, type Font } from "./truetype";
import { Page, rgb } from "./writer";

/**
 * The two documents a simulated supplier event delivers: the invoice and the
 * credit note.
 *
 * They are laid out in the prototype's own visual language, because that is the
 * whole point of offering them - a reviewer who clicks "download" should get
 * something that plainly belongs to the same product as the screen they clicked
 * it from. Containers square, controls round, lowercase chrome, the indigo
 * block on the grey field, and the ◆ coral tag that means simulated.
 *
 * Two deliberate absences:
 *
 * - **No prices.** `initial.json` carries quantities only, and the working
 *   agreement forbids inventing a price. The document says so in as many words
 *   rather than leaving a blank column a reader might fill in themselves.
 * - **No client identity.** No logo, no mark, no wordmark, and no named
 *   bill-to. The assignment is an exercise and does not imply the client
 *   commissioned or endorsed any of this, so the styling is borrowed and the
 *   identity is not.
 */

// ---------------------------------------------------------------------------
// Wording
// ---------------------------------------------------------------------------

/*
 * The document's own strings, and not in `src/lib/i18n/` on purpose.
 *
 * A dictionary entry there must exist in all three languages or the typecheck
 * fails, and Arabic cannot be set here: this writer embeds Montserrat, which
 * has no Arabic glyphs, and Arabic needs shaping a PDF text run does not do.
 * Rather than ship a page of empty boxes, the document follows the reader's
 * language where it can and otherwise arrives in the language it was issued
 * in - which is also how a real scan behaves. The dialog that offers the
 * download says so, in all three.
 */
type DocStrings = {
  invoiceKicker: string;
  creditKicker: string;
  simulated: string;
  says: string;
  thRecord: string;
  thDescription: string;
  thQuantity: string;
  invoiceLine: (part: string, notes: string) => string;
  creditLine: (invoiceId: string, n: number) => string;
  figInvoiced: string;
  figNotes: string;
  figOrder: string;
  figCredited: string;
  figAgainst: string;
  limitsHeading: string;
  invoiceLimits: string;
  creditLimits: (invoiceId: string) => string;
  simHeading: string;
  simBody: string;
  footer: string;
  generated: (stamp: string) => string;
};

const STRINGS: Record<"en" | "de", DocStrings> = {
  en: {
    invoiceKicker: "supplier invoice",
    creditKicker: "supplier credit note",
    simulated: "Simulated",
    says: "what this document says",
    thRecord: "Record",
    thDescription: "Description",
    thQuantity: "Quantity",
    invoiceLine: (part, notes) => `Invoice for ${part}, billed against ${notes}.`,
    creditLine: (invoiceId, n) =>
      `Credit for ${n} damaged unit(s) reported at receipt, against ${invoiceId}.`,
    figInvoiced: "Invoiced",
    figNotes: "Delivery notes",
    figOrder: "Order",
    figCredited: "Credited",
    figAgainst: "Against",
    limitsHeading: "what it does not say",
    invoiceLimits:
      "Quantities only. The exercise dataset carries no prices, so none appear here and none were invented for this document. An invoice states what the supplier billed; it does not know what was counted in at the bay, or what arrived damaged.",
    creditLimits: (invoiceId) =>
      `${invoiceId} is not edited. A supplier correction arrives as its own record, so the original invoice and the correction both stay readable afterwards. Quantities only: the exercise dataset carries no prices and none were invented here.`,
    simHeading: "Simulated document",
    simBody:
      "Generated by the C04 prototype to stand in for a scan the facilitator would otherwise hand over. Nothing external was executed: no supplier was contacted, no inventory was updated and no accounting entry was made.",
    footer: "Synthetic exercise data · case C04 · not a real supplier document",
    generated: (stamp) => `Generated ${stamp}`,
  },
  de: {
    invoiceKicker: "lieferantenrechnung",
    creditKicker: "gutschrift des lieferanten",
    simulated: "Simuliert",
    says: "was dieses dokument sagt",
    thRecord: "Beleg",
    thDescription: "Beschreibung",
    thQuantity: "Menge",
    invoiceLine: (part, notes) => `Rechnung über ${part}, abgerechnet gegen ${notes}.`,
    creditLine: (invoiceId, n) =>
      `Gutschrift über ${n} bei der Annahme als beschädigt gemeldete(s) Stück, gegen ${invoiceId}.`,
    figInvoiced: "Berechnet",
    figNotes: "Lieferscheine",
    figOrder: "Bestellung",
    figCredited: "Gutgeschrieben",
    figAgainst: "Gegen",
    limitsHeading: "was es nicht sagt",
    invoiceLimits:
      "Nur Mengen. Der Übungsdatensatz enthält keine Preise; es stehen deshalb keine in diesem Dokument, und es wurden auch keine erfunden. Eine Rechnung sagt, was der Lieferant berechnet hat — sie weiß nicht, was an der Rampe gezählt wurde oder was beschädigt ankam.",
    creditLimits: (invoiceId) =>
      `${invoiceId} wird nicht geändert. Eine Korrektur des Lieferanten kommt als eigener Beleg, damit Rechnung und Korrektur danach beide lesbar bleiben. Nur Mengen: der Übungsdatensatz enthält keine Preise, und es wurden hier keine erfunden.`,
    simHeading: "Simuliertes Dokument",
    simBody:
      "Vom C04-Prototyp erzeugt, stellvertretend für einen Scan, den sonst die Moderation übergeben würde. Nichts wurde nach außen ausgeführt: kein Lieferant kontaktiert, kein Bestand aktualisiert, keine Buchung erstellt.",
    footer: "Synthetische Übungsdaten · Fall C04 · kein echtes Lieferantendokument",
    generated: (stamp) => `Erzeugt ${stamp}`,
  },
};

/** English is the fallback, the same way `getDict` falls back. */
export const docLocale = (locale: string) => (locale === "de" ? "de" : "en");

// ---------------------------------------------------------------------------
// Faces
// ---------------------------------------------------------------------------

/*
 * Read once per process, not per request - the two files are ~240 KB and every
 * download would otherwise re-parse them. Lazy, so nothing touches the disk
 * while Next is collecting routes at build time.
 *
 * No mono face. Record ids are set in the semibold instead: a third embedded
 * font to letter-space `INV-1` is not worth 120 KB on every download.
 */
let faces: { regular: Font; semibold: Font } | null = null;

function fonts() {
  if (!faces) {
    const dir = join(process.cwd(), "src/lib/pdf/fonts");
    faces = {
      regular: loadFont(join(dir, "Montserrat-Regular.ttf"), "Montserrat"),
      semibold: loadFont(join(dir, "Montserrat-SemiBold.ttf"), "Montserrat-SemiBold"),
    };
  }
  return faces;
}

// ---------------------------------------------------------------------------
// Layout
// ---------------------------------------------------------------------------

const M = 48; // page margin
const PAD = 16; // padding inside a block
const BAND = 150; // the indigo hero block

/** A container: square, hairline border, white. The `Card` of this document. */
function block(p: Page, x: number, y: number, w: number, h: number, fill = c.surface) {
  p.rect(x, y, w, h, rgb(c.line));
  p.rect(x + 0.75, y + 0.75, w - 1.5, h - 1.5, rgb(fill));
}

/** Baseline that puts a cap-height line on the centre of a band. */
function centred(cy: number, size: number, font: Font) {
  return cy + ((font.capHeight / 1000) * size) / 2;
}

/** The ◆ + word tag, as a round control on a square page. Returns its width. */
function simulatedTag(
  p: Page,
  x: number,
  y: number,
  label: string,
  fill: string,
  ink: string,
) {
  const { semibold } = fonts();
  const size = 9.5;
  const h = 19;
  const w = p.measure(label, { font: semibold, size }) + 32;
  p.pill(x, y, w, h, rgb(fill));
  p.diamond(x + 13, y + h / 2, 3.1, rgb(ink));
  p.text(label, x + 21, centred(y + h / 2, size, semibold), {
    font: semibold,
    size,
    color: rgb(ink),
  });
  return w;
}

type Cell = { label: string; value: string; hint?: string };

/** The figures strip off the evidence screen: square cells, hairline gaps. */
function figures(p: Page, x: number, y: number, w: number, cells: Cell[]) {
  const { regular, semibold } = fonts();
  const h = 78;
  p.rect(x, y, w, h, rgb(c.line));
  const cw = (w - 1.5 - (cells.length - 1)) / cells.length;

  cells.forEach((cell, i) => {
    const cx = x + 0.75 + i * (cw + 1);
    p.rect(cx, y + 0.75, cw, h - 1.5, rgb(c.surface));
    p.text(cell.label, cx + 14, p.lineTop(y + 14, 9, semibold), {
      font: semibold,
      size: 9,
      color: rgb(c.faint),
    });
    p.text(cell.value, cx + 14, p.lineTop(y + 28, 23, semibold), {
      font: semibold,
      size: 23,
      color: rgb(c.foreground),
    });
    if (cell.hint) {
      p.text(cell.hint, cx + 14, p.lineTop(y + 60, 8.5, regular), {
        font: regular,
        size: 8.5,
        color: rgb(c.faint),
      });
    }
  });
  return y + h;
}

/** A lowercase section label, matching `SectionTitle`. */
function sectionTitle(p: Page, x: number, y: number, text: string) {
  const { semibold } = fonts();
  p.text(text, x, p.lineTop(y, 9.5, semibold), {
    font: semibold,
    size: 9.5,
    color: rgb(c.faint),
  });
  return y + 22;
}

// ---------------------------------------------------------------------------
// The documents
// ---------------------------------------------------------------------------

export type DocumentKind = "invoice" | "credit-note";

export function renderDocument(
  kind: DocumentKind,
  facts: EventFacts,
  locale: "en" | "de",
): { body: Buffer; filename: string; title: string } {
  const s = STRINGS[locale];
  const { regular, semibold } = fonts();
  const p = new Page();
  const W = p.width;
  const CW = W - M * 2;

  const isInvoice = kind === "invoice";
  const id = isInvoice ? facts.invoiceId : facts.creditId;
  const notes = facts.noteIds.join(" + ");

  // The grey field everything floats on.
  p.rect(0, 0, W, p.height, rgb(c.background));

  // --- the indigo block -----------------------------------------------------
  p.rect(0, 0, W, BAND, rgb(c.brand));
  p.rect(M, 44, 10, 10, rgb(c.brandInk));
  p.text(
    isInvoice ? s.invoiceKicker : s.creditKicker,
    M + 18,
    p.lineTop(44, 10.5, semibold),
    { font: semibold, size: 10.5, color: rgb(c.brandSoft) },
  );
  p.text(id, M, p.lineTop(72, 34, semibold), {
    font: semibold,
    size: 34,
    color: rgb(c.brandInk),
  });
  p.text(
    isInvoice
      ? `${facts.part} · ${facts.orderId}`
      : `${facts.invoiceId} · ${facts.orderId}`,
    M,
    p.lineTop(118, 11, regular),
    { font: regular, size: 11, color: rgb(c.brandSoft) },
  );

  const tagWidth = p.measure(s.simulated, { font: semibold, size: 9.5 }) + 32;
  simulatedTag(p, W - M - tagWidth, 44, s.simulated, c.simSoft, c.sim);

  // --- the figures ----------------------------------------------------------
  let y = BAND + 30;
  y = figures(
    p,
    M,
    y,
    CW,
    isInvoice
      ? [
          { label: s.figInvoiced, value: String(facts.invoiceQty), hint: facts.part },
          { label: s.figNotes, value: String(facts.noteIds.length), hint: notes },
          { label: s.figOrder, value: facts.orderId },
        ]
      : [
          { label: s.figCredited, value: String(facts.creditQty), hint: facts.part },
          { label: s.figAgainst, value: facts.invoiceId, hint: notes },
          { label: s.figOrder, value: facts.orderId },
        ],
  );

  // --- what the document says ----------------------------------------------
  y = sectionTitle(p, M, y + 30, s.says);

  const description = isInvoice
    ? s.invoiceLine(facts.part, notes)
    : s.creditLine(facts.invoiceId, facts.creditQty);
  const qtyColumn = 78;
  const descWidth = CW - PAD * 2 - 74 - qtyColumn;
  const descLines = p.wrap(description, descWidth, { font: regular, size: 10 });
  const rowHeight = Math.max(34, descLines.length * 14 + 20);
  const tableHeight = 26 + rowHeight;

  block(p, M, y, CW, tableHeight);
  const th = { font: regular, size: 8.5, color: rgb(c.faint) } as const;
  p.text(s.thRecord, M + PAD, p.lineTop(y + 8, 8.5, regular), th);
  p.text(s.thDescription, M + PAD + 74, p.lineTop(y + 8, 8.5, regular), th);
  p.text(s.thQuantity, M + CW - PAD, p.lineTop(y + 8, 8.5, regular), {
    ...th,
    align: "end",
  });
  p.line(M + 0.75, y + 26, M + CW - 0.75, y + 26, rgb(c.line));

  p.text(id, M + PAD, p.lineTop(y + 36, 10, semibold), {
    font: semibold,
    size: 10,
    color: rgb(c.foreground),
  });
  descLines.forEach((line, i) => {
    p.text(line, M + PAD + 74, p.lineTop(y + 36 + i * 14, 10, regular), {
      font: regular,
      size: 10,
      color: rgb(c.muted),
    });
  });
  p.text(
    String(isInvoice ? facts.invoiceQty : facts.creditQty),
    M + CW - PAD,
    p.lineTop(y + 36, 10, semibold),
    { font: semibold, size: 10, color: rgb(c.foreground), align: "end" },
  );
  y += tableHeight;

  // --- what it does not say -------------------------------------------------
  y = sectionTitle(p, M, y + 30, s.limitsHeading);
  const limits = isInvoice ? s.invoiceLimits : s.creditLimits(facts.invoiceId);
  const limitLines = p.wrap(limits, CW - PAD * 2, { font: regular, size: 10 });
  const limitsHeight = limitLines.length * 15 + PAD * 2 - 2;
  block(p, M, y, CW, limitsHeight);
  limitLines.forEach((line, i) => {
    p.text(line, M + PAD, p.lineTop(y + PAD - 3 + i * 15, 10, regular), {
      font: regular,
      size: 10,
      color: rgb(c.muted),
    });
  });
  y += limitsHeight;

  // --- the label the exercise requires --------------------------------------
  // Anchored to the foot of the page rather than to the block above it. A
  // document runs short or long depending on how much the supplier billed; the
  // label that says none of this is real should sit in the same place either
  // way, and it leaves the whitespace where a document normally has it.
  const simLines = p.wrap(s.simBody, CW - PAD * 2, { font: regular, size: 9.5 });
  const simHeight = 30 + simLines.length * 14 + PAD;
  y = Math.max(y + 30, p.height - 64 - 30 - simHeight);
  p.rect(M, y, CW, simHeight, rgb(c.sim));
  p.rect(M + 0.75, y + 0.75, CW - 1.5, simHeight - 1.5, rgb(c.simSoft));
  p.diamond(M + PAD + 4, y + PAD + 1, 3.6, rgb(c.sim));
  p.text(s.simHeading, M + PAD + 13, centred(y + PAD + 1, 10, semibold), {
    font: semibold,
    size: 10,
    color: rgb(c.sim),
  });
  simLines.forEach((line, i) => {
    p.text(line, M + PAD, p.lineTop(y + 28 + i * 14, 9.5, regular), {
      font: regular,
      size: 9.5,
      color: rgb(c.foreground),
    });
  });

  // --- footer ---------------------------------------------------------------
  const foot = p.height - 64;
  p.line(M, foot, W - M, foot, rgb(c.line));
  p.text(s.footer, M, p.lineTop(foot + 12, 9, semibold), {
    font: semibold,
    size: 9,
    color: rgb(c.faint),
  });
  const stamp = new Date().toISOString().replace("T", " ").slice(0, 16);
  p.text(s.generated(`${stamp} UTC`), W - M, p.lineTop(foot + 12, 9, regular), {
    font: regular,
    size: 9,
    color: rgb(c.faint),
    align: "end",
  });

  const title = `${id} — ${isInvoice ? s.invoiceKicker : s.creditKicker}`;
  return { body: p.render(title), filename: `${id}.pdf`, title };
}
